### ISSUE TITLE
Incompatibility with GNU/Linux and Mac OS X

### ISSUE THREAD

**Issue by nixnuex** [ehajo/arduino-boards#1]
On Mac OS X 10.11.6 and Arduino 1.6.9, when trying to install the aTeVaL board through Arduino's Board Manager following http://dokuwiki.ehajo.de/artikel:arduino-boardmanager I only get the error

`Tool avrdude is not available for your operating system.`

Looking into `package_ehajo_index.json` the problem seems to be the dependency on "avrdude" which is just supplied for Windows. I have avrdude-6.3 installed system-wide from a different source. Is it somehow possible to remove this dependency and let the user deal with it?

**Comment by ehajo** [comment]
Removed avrdude dependency on v1.0.1.
