### ISSUE TITLE
Package URLs have changed

### ISSUE THREAD

**Issue by fabian-schlegel** [ehajo/arduino-boards#1]
Hey Hajo,

the package URLs in the [index JSON file](https://github.com/ehajo/arduino-boards/blob/main/package_ehajo_index.json) aren't working anymore due to GitHub branch name changes.

The old URL is something like: https://github.com/ehajo/arduino-boards/raw/master/packages/ehajo-avr-2.2.0.zip

But the correct URL should be: https://github.com/ehajo/arduino-boards/raw/main/packages/ehajo-avr-2.2.0.zip

**Comment by fabian-schlegel** [comment]
Since I've no access to create a PR, the quick workaround is:

- Download the JSON file
- Fix the URLs and save the file
- In the Arduino Studio Preferences, put the URL to the locally saved file: file:///what/ever/package_ehajo_index.json
- "Mach was Gescheid's!"

**Comment by ehajo** [comment]
Closed, thank you!
